name: ocr-latex
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - numpy=1.25.2
  - scipy
  - pip
  - pip:
    - datasets==2.20.0
    - evaluate==0.4.2
    - transformers==4.32.0
    - peft==0.11.1
    - tqdm==4.66.4
    - huggingface-hub
    - accelerate
    - tensorboard
    - wandb
    - matplotlib
    - seaborn
    - nltk